# Generated by Django 4.0.6 on 2022-07-27 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Тип транспорта', 'verbose_name_plural': 'Типы транспорта'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['title'], 'verbose_name': 'Транспортное средство', 'verbose_name_plural': 'Транстпортные средства'},
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='vehicles', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='image',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicle.vehicle', verbose_name='транспорт'),
        ),
    ]
