# Generated by Django 4.0.6 on 2022-07-28 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_alter_like_author_alter_like_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='vehicle.vehicle', verbose_name='Транспорт'),
        ),
    ]
