# Generated by Django 4.0.6 on 2022-07-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_alter_rating_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступен для покупки'),
        ),
    ]
