# Generated by Django 4.0.6 on 2022-07-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_myuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(default='/home/esentur/Desktop/py21/django/auto_true_hackathon_v2/static/my_static_pic/default-avatar.png', upload_to='users'),
        ),
    ]
