# Generated by Django 4.0.6 on 2022-07-28 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_myuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='avatar',
        ),
    ]
