# Generated by Django 4.0.6 on 2022-07-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_purchase_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтвержден ли'),
        ),
    ]
